apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
   app: drupal
  name: drupal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: drupal
    spec:
      initContainers:
      - image: drupal:8.6
        name: init-sites-volume
        command: [ "/bin/bash", "-c" ]
        args: [ 'cp -r /var/www/html/sites/ /data/; chown www-data:www-data /data/ -R' ]
        volumeMounts:
        - mountPath: "/data"
          name: drupal-pvc-vol
      containers:
      - image: drupal:8.6
        name: drupal
        volumeMounts:
        - mountPath: "/var/www/html/modules"
          subPath: "modules"
          name: drupal-pvc-vol
        - mountPath: "/var/www/html/profiles"
          subPath: "profiles"
          name: drupal-pvc-vol
        - mountPath: "/var/www/html/sites"
          subPath: "sites"
          name: drupal-pvc-vol
        - mountPath: "/var/www/html/themes"
          subPath: "themes"
          name: drupal-pvc-vol
      volumes:
      - name: drupal-pvc-vol
        persistentVolumeClaim:
          claimName: drupal-pvc
