apiVersion: v1
kind: Service
metadata:
  namespace: development
  creationTimestamp: null
  labels:
    run: jekyll
  name: jekyll
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 4000
    nodePort: 30097
  type: NodePort
  selector:
    run: jekyll
